[package]
name = "axum-prom"
version = "0.4.0"
edition = "2021"

[dependencies]
axum = "0.8"
futures-core = "0.3"
http = "1"
pin-project = "1"
prometheus = "0.13"
tower = "*"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
